<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DJQBPR7" failures="1" tests="2" name="Runner.TestRunner" time="4.748" errors="0" timestamp="2021-10-10T15:08:36 HKT" skipped="0">
  <testcase classname="Runner.TestRunner" name="runScenario" time="3.920"/>
  <system-out/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.828">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at StepDefinition.LoginAPIStep.statusCodeShouldBe(LoginAPIStep.java:77)
at âœ½.status code should be 200(file:///F:/Project/API_Test/src/test/resources/features/LoginAPI.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.TestRunner -->
